export interface SymbolInfo {
  s: string;
  n: string;
  p: number;
}

export const BIST_SYMBOLS: SymbolInfo[] = [
  {s:'THYAO',n:'Türk Hava Yolları',p:305},{s:'GARAN',n:'Garanti BBVA',p:84},{s:'ASELS',n:'Aselsan',p:62},
  {s:'AKBNK',n:'Akbank',p:42},{s:'YKBNK',n:'Yapı Kredi',p:28},{s:'ISCTR',n:'İş Bankası C',p:11},
  {s:'KCHOL',n:'Koç Holding',p:212},{s:'SAHOL',n:'Sabancı Holding',p:92},{s:'TCELL',n:'Turkcell',p:78},
  {s:'BIMAS',n:'BİM Mağazalar',p:395},{s:'EREGL',n:'Ereğli Demir Çelik',p:48},{s:'TUPRS',n:'Tüpraş',p:174},
  {s:'SISE',n:'Şişecam',p:52},{s:'FROTO',n:'Ford Otosan',p:950},{s:'TOASO',n:'Tofaş',p:280},
  {s:'PGSUS',n:'Pegasus',p:880},{s:'ENKAI',n:'Enka İnşaat',p:45},{s:'VESTL',n:'Vestel',p:38},
  {s:'ARCLK',n:'Arçelik',p:165},{s:'PETKM',n:'Petkim',p:22},{s:'SASA',n:'SASA Polyester',p:38},
  {s:'HEKTS',n:'Hektaş',p:15},{s:'KOZAL',n:'Koza Altın',p:250},{s:'KOZAA',n:'Koza Madencilik',p:85},
  {s:'TAVHL',n:'TAV Havalimanları',p:105},{s:'TKFEN',n:'Tekfen Holding',p:120},{s:'DOHOL',n:'Doğan Holding',p:18},
  {s:'EKGYO',n:'Emlak Konut GYO',p:14},{s:'MGROS',n:'Migros',p:420},{s:'TTKOM',n:'Türk Telekom',p:46},
  {s:'TTRAK',n:'Türk Traktör',p:650},{s:'OTKAR',n:'Otokar',p:780},{s:'AEFES',n:'Anadolu Efes',p:320},
  {s:'ULKER',n:'Ülker',p:145},{s:'CCOLA',n:'Coca-Cola İçecek',p:880},{s:'TSKB',n:'TSKB',p:18},
  {s:'VAKBN',n:'VakıfBank',p:22},{s:'HALKB',n:'Halkbank',p:18},{s:'ALARK',n:'Alarko Holding',p:55},
  {s:'ISGYO',n:'İş GYO',p:12},{s:'MPARK',n:'MLP Sağlık',p:210},{s:'SOKM',n:'Şok Marketler',p:25},
  {s:'GESAN',n:'Gesan Elektrik',p:42},{s:'CIMSA',n:'Çimsa',p:42},{s:'KCAER',n:'Kocaer Çelik',p:35},
  {s:'KORDS',n:'Kordsa',p:110},{s:'AYGAZ',n:'Aygaz',p:48},{s:'BERA',n:'Bera Holding',p:8},
  {s:'DOAS',n:'Doğuş Otomotiv',p:280},{s:'EGEEN',n:'Ege Endüstri',p:1200},{s:'ENJSA',n:'Enerjisa',p:52},
  {s:'OYAKC',n:'Oyak Çimento',p:32},{s:'ASTOR',n:'Astor Enerji',p:85},{s:'BRISA',n:'Brisa',p:195},
  {s:'CEMTS',n:'Çemtaş',p:38},{s:'DEVA',n:'Deva Holding',p:115},{s:'ECILC',n:'Eczacıbaşı İlaç',p:8},
  {s:'GUBRF',n:'Gübre Fabrikaları',p:160},{s:'KONTR',n:'Kontrolmatik',p:115},{s:'LOGO',n:'Logo Yazılım',p:250},
  {s:'MAVI',n:'Mavi Giyim',p:165},{s:'NETAS',n:'Netaş',p:95},{s:'ODAS',n:'Odaş Elektrik',p:12},
  {s:'SARKY',n:'Sarkuysan',p:28},{s:'TABGD',n:'Tabgıda',p:14},{s:'TURSG',n:'Türkiye Sigorta',p:16},
  {s:'ULUUN',n:'Ulusoy Un',p:45},{s:'VERTU',n:'Verusaturk GYO',p:3},{s:'ZOREN',n:'Zorlu Enerji',p:4},
  {s:'AKSEN',n:'Aksa Enerji',p:25},{s:'ANACM',n:'Anadolu Cam',p:8},{s:'ANHYT',n:'Anadolu Hayat',p:14},
  {s:'ANSGR',n:'Anadolu Sigorta',p:8},{s:'ARSAN',n:'Arsan Tekstil',p:10},{s:'ASUZU',n:'Anadolu Isuzu',p:45},
  {s:'BAGFS',n:'Bagfaş',p:85},{s:'BIENY',n:'BienYapı',p:4},{s:'BJKAS',n:'Beşiktaş JK',p:8},
  {s:'BTCIM',n:'Batıçim',p:42},{s:'BUCIM',n:'Bursa Çimento',p:28},{s:'BURCE',n:'Burçelik',p:12},
  {s:'CRFSA',n:'CarrefourSA',p:48},{s:'DGATE',n:'D-Gate',p:18},{s:'DITAS',n:'Ditaş Doğan',p:42},
  {s:'EKSUN',n:'Ekiz Sun',p:8},{s:'EPLAS',n:'Egeplast',p:18},{s:'FONET',n:'Fonet',p:22},
  {s:'GENTS',n:'Gentaş',p:14},{s:'GLYHO',n:'Global Yatırım',p:15},{s:'GOKNR',n:'Göknur Gıda',p:5},
  {s:'GOLTS',n:'Goldaş',p:18},{s:'GSDHO',n:'GSD Holding',p:5},{s:'HUBVC',n:'Hub Girişim',p:115},
  {s:'INDES',n:'İndeks Bilgisayar',p:22},{s:'ISMEN',n:'İş Yatırım',p:12},{s:'KAREL',n:'Karel Elektronik',p:18},
  {s:'KARSN',n:'Karsan',p:18},{s:'KATMR',n:'Katmerciler',p:22},{s:'KLGYO',n:'Kiler GYO',p:3},
  {s:'KLMSN',n:'Klimasan',p:95},{s:'KNFRT',n:'Konfrut',p:42},{s:'KRDMD',n:'KARDEMİR D',p:22},
  {s:'KRONT',n:'Kron Telekom',p:35},{s:'LIDER',n:'Lider Faktoring',p:3},{s:'MACKO',n:'Maço Gıda',p:28},
  {s:'MAKTK',n:'Maktek',p:95},{s:'MEGAP',n:'Mega Polietilen',p:8},{s:'MEPET',n:'Mepet Petrol',p:5},
  {s:'MERIT',n:'Merit Turizm',p:12},{s:'MERKO',n:'Merko Gıda',p:5},{s:'MTRKS',n:'Matreks',p:12},
  {s:'NTHOL',n:'Net Holding',p:28},{s:'NUHCM',n:'Nuh Çimento',p:55},{s:'ORGE',n:'Orge Enerji',p:28},
  {s:'OSTIM',n:'OSTİM Endüstriyel',p:35},{s:'OZKGY',n:'Özak GYO',p:18},{s:'PARSN',n:'Parsan',p:42},
  {s:'PENTA',n:'Penta Teknoloji',p:75},{s:'POLHO',n:'Polisan Holding',p:12},{s:'PRDGS',n:'Pardus Girişim',p:5},
  {s:'PRKAB',n:'Türk Prysmian',p:45},{s:'QNBFB',n:'QNB Finansbank',p:28},{s:'SAFKR',n:'Safkar Ege',p:18},
  {s:'SANFM',n:'Sanifoam',p:12},{s:'SEKUR',n:'Sekuro Plastik',p:3},{s:'SNGYO',n:'Sinpaş GYO',p:5},
  {s:'SKBNK',n:'Şekerbank',p:5},{s:'SMART',n:'SmartGüneş',p:12},{s:'SMRTG',n:'Smart Güneş',p:14},
  {s:'SUWEN',n:'Suwen',p:14},{s:'TATGD',n:'Tat Gıda',p:42},{s:'TBORG',n:'Tuborg',p:95},
  {s:'TDGYO',n:'Trend GYO',p:5},{s:'TEKTU',n:'Tek-Art Turizm',p:8},{s:'TMSN',n:'Tümosan',p:42},
  {s:'TRILC',n:'Turkcell İletişim',p:78},{s:'TRGYO',n:'Torunlar GYO',p:12},{s:'TUKAS',n:'Tukaş',p:8},
  {s:'TUREX',n:'Tureks',p:15},{s:'ULUSE',n:'Ulusoy Elektrik',p:22},{s:'UNYEC',n:'Ünye Çimento',p:18},
  {s:'VAKFN',n:'Vakıf Fin. Kiralama',p:12},{s:'VAKKO',n:'Vakko',p:28},{s:'VESBE',n:'Vestel Beyaz',p:62},
  {s:'VKFYO',n:'Vakıf GYO',p:8},{s:'VOCAS',n:'Voçaş',p:5},{s:'YEOTK',n:'Yeo Teknoloji',p:12},
  {s:'YGYO',n:'Yeşil GYO',p:3},{s:'YKSLN',n:'Yüksel İnşaat',p:5},{s:'YUNSA',n:'Yünsa',p:65},
  {s:'YYAPI',n:'Yayla Agro',p:18},{s:'ZRGYO',n:'Ziraat GYO',p:5},{s:'ACSEL',n:'Acıselsan',p:145},
  {s:'ADEL',n:'Adel Kalemcilik',p:280},{s:'AFYON',n:'Afyon Çimento',p:12},{s:'AGESA',n:'AgeSA Hayat',p:45},
  {s:'AGHOL',n:'AG Holding',p:12},{s:'AHGAZ',n:'Ahlatcı Doğalgaz',p:8},{s:'AKFGY',n:'Akfen GYO',p:18},
  {s:'AKFYE',n:'Akfen YEO',p:25},{s:'AKSGY',n:'Akiş GYO',p:5},{s:'AKSUE',n:'Aksu Enerji',p:8},
  {s:'AKYHO',n:'Akdeniz Yatırım',p:8},{s:'ALCTL',n:'Alcatel Lucent',p:12},{s:'ALFAS',n:'Alfa Solar',p:42},
  {s:'ALGYO',n:'ALarko GYO',p:55},{s:'ALKA',n:'Alka Holding',p:12},{s:'ALMAD',n:'Altınyağ Madencilik',p:14},
  {s:'ANELE',n:'Anel Elektrik',p:8},{s:'ANGEN',n:'Anatolia Genetik',p:3},{s:'ARENA',n:'Arena Bilgisayar',p:55},
  {s:'ARMDA',n:'Armada Bilgisayar',p:8},{s:'ARZUM',n:'Arzum',p:28},{s:'ATAGY',n:'ATA GYO',p:3},
  {s:'ATEKS',n:'Akal Tekstil',p:8},{s:'ATLAS',n:'Atlas Yatırım',p:5},{s:'AVHOL',n:'Avrupa Holding',p:3},
  {s:'AVOD',n:'A.V.O.D Gıda',p:5},{s:'AVPGY',n:'Avrasya GYO',p:3},{s:'AVTUR',n:'Avrasya Petrol',p:5},
  {s:'AYCES',n:'Altınyunus Çeşme',p:22},{s:'AYDEM',n:'Aydem Enerji',p:12},{s:'AYES',n:'Ayes Çelik',p:8},
  {s:'BAKAB',n:'Bak Ambalaj',p:28},{s:'BALAT',n:'Balatacilar',p:12},{s:'BANVT',n:'Banvit',p:42},
  {s:'BARMA',n:'Barem Ambalaj',p:8},{s:'BASGZ',n:'Başgazete',p:5},{s:'BAYRK',n:'Bayrak Taban',p:3},
  {s:'BFREN',n:'Bosch Fren',p:1800},{s:'BINHO',n:'BİN Holding',p:5},{s:'BIOEN',n:'Biotrend Enerji',p:8},
  {s:'BIZIM',n:'Bizim Mağazaları',p:22},{s:'BLCYT',n:'Bilici Yatırım',p:12},{s:'BMSCH',n:'Bosch Sanayi',p:3200},
  {s:'BMSTL',n:'BMS Çelik',p:8},{s:'BNTAS',n:'Bantaş Ambalaj',p:5},{s:'BOSSA',n:'Bossa',p:8},
  {s:'BRKSN',n:'Berkosan Yalıtım',p:22},{s:'BRLSM',n:'Birleşim Mühendislik',p:55},{s:'BRMEN',n:'Birlik Mensucat',p:3},
  {s:'BRYAT',n:'Borusan Yatırım',p:55},{s:'BSOKE',n:'Batısöke Çimento',p:18},{s:'BTCIM',n:'Batıçim',p:42},
  {s:'CANTE',n:'Çan Termik',p:5},{s:'CASA',n:'Casa Emtia',p:3},{s:'CELHA',n:'Çelik Halat',p:38},
  {s:'CEMAS',n:'Çemaş Döküm',p:5},{s:'CEMZY',n:'Çemtaş Ağır San',p:18},{s:'CEOEM',n:'CEO Event',p:3},
  {s:'CLEBI',n:'Çelebi Havacılık',p:350},{s:'CONSE',n:'Consus Enerji',p:5},{s:'CRDFA',n:'CarrefourSA',p:18},
  {s:'CUSAN',n:'Çuhadaroğlu',p:22},{s:'CVKMD',n:'CVK Madencilik',p:5},{s:'DAGHL',n:'Dağ Holding',p:8},
  {s:'DAPGM',n:'DAP Gayrimenkul',p:3},{s:'DARDL',n:'Dardanel',p:14},{s:'DENGE',n:'Denge Holding',p:3},
  {s:'DERHL',n:'Dereli Holding',p:3},{s:'DESPC',n:'Despec Bilgisayar',p:55},{s:'DESA',n:'Desa Deri',p:42},
  {s:'DGNMO',n:'Doğanlar Mobilya',p:5},{s:'DMSAS',n:'Demisaş Döküm',p:18},{s:'DNISI',n:'Deniz Yatırım',p:3},
  {s:'DOBUR',n:'Doğuş Burger',p:18},{s:'DURDO',n:'Duran Doğan',p:18},{s:'DYOBY',n:'Dyo Boya',p:12},
  {s:'DZGYO',n:'Deniz GYO',p:3},{s:'EDATA',n:'E-Data Teknoloji',p:3},{s:'EDIP',n:'Edip Gayrimenkul',p:3},
  {s:'EGPRO',n:'Ege Profil',p:68},{s:'EGSER',n:'Ege Seramik',p:12},{s:'EMKEL',n:'Emkel Elektrik',p:3},
  {s:'EMNIS',n:'Eminiş Ambalaj',p:8},{s:'ENSRI',n:'Enerji SA Üretim',p:5},{s:'ERBOS',n:'Erbosan',p:55},
  {s:'ERCB',n:'Erciyes Çelik',p:5},{s:'ERSU',n:'Ersu Meyve',p:8},{s:'ESCAR',n:'Escar Filo',p:18},
  {s:'ESCOM',n:'Escort Teknoloji',p:5},{s:'ESEN',n:'Esenboğa Elektrik',p:5},{s:'ETILR',n:'Etiler Gıda',p:8},
  {s:'ETYAT',n:'Euro Trend Yatırım',p:3},{s:'EUHOL',n:'Euro Holding',p:3},{s:'EUKYO',n:'Euro Kapital',p:3},
  {s:'EUPWR',n:'Euro Power',p:3},{s:'EUREN',n:'Euro Enerji',p:8},{s:'FADE',n:'Fade Gıda',p:5},
  {s:'FENER',n:'Fenerbahçe',p:55},{s:'FLAP',n:'F-Yapı',p:5},{s:'FMIZP',n:'F&M İzmit Piston',p:85},
  {s:'FORMT',n:'Formet Metal',p:8},{s:'FORTE',n:'Forte Bilgi',p:5},{s:'FRIGO',n:'Frigo-Pak',p:22},
  {s:'GARFA',n:'Gar Finans',p:5},{s:'GEDIK',n:'Gedik Yatırım',p:3},{s:'GEDZA',n:'Gediz Ambalaj',p:5},
  {s:'GENIL',n:'Genişletilmiş İleri',p:3},{s:'GEREL',n:'Gersan Elektrik',p:3},{s:'GLBMD',n:'Global Menkul',p:8},
  {s:'GLCVY',n:'Gelecek Varlık',p:3},{s:'GMTAS',n:'Gimat Mağazacılık',p:5},{s:'GOODY',n:'Goodyear',p:245},
  {s:'GRNYO',n:'Garanti Yatırım',p:3},{s:'GRSEL',n:'GSD Elektrik',p:3},{s:'GSRAY',n:'Galatasaray',p:22},
  {s:'GWIND',n:'Galata Wind',p:18},{s:'HATEK',n:'Hateks',p:12},{s:'HDFGS',n:'Hedef Gıda',p:5},
  {s:'HTTBT',n:'Hitit Bilgisayar',p:350},{s:'HUNER',n:'Hun Enerji',p:5},{s:'HURGZ',n:'Hürriyet Gazete',p:3},
  {s:'ICBCT',n:'ICBC Turkey',p:8},{s:'IDEAS',n:'İdea Strateji',p:3},{s:'IDGYO',n:'İdealist GYO',p:3},
  {s:'IHEVA',n:'İhlas Ev Aletleri',p:3},{s:'IHGZT',n:'İhlas Gazetecilik',p:3},{s:'IHLGM',n:'İhlas Girişim',p:3},
  {s:'IHYAY',n:'İhlas Yayın',p:3},{s:'IMASM',n:'İmas Makina',p:5},{s:'INGRM',n:'İngram Micro',p:3},
  {s:'INTEM',n:'İntem',p:5},{s:'INVEO',n:'İnveo Yatırım',p:12},{s:'IPEKE',n:'İpek Doğal',p:18},
  {s:'ISGSY',n:'İş Gayrimenkul',p:5},{s:'ISBIR',n:'İşbir Sentetik',p:38},{s:'ISKPL',n:'İskenderun B',p:3},
  {s:'ISSEN',n:'İş Sanayi',p:8},{s:'ITTFH',n:'İttifak Holding',p:12},{s:'IZFAS',n:'İz Faizsiz',p:3},
  {s:'IZINV',n:'İz Yatırım',p:3},{s:'JANTS',n:'Jantsa Jant',p:38},{s:'KAPLM',n:'Kaplamin',p:5},
  {s:'KARYE',n:'Kar Yatırım',p:3},{s:'KAYSE',n:'Kayseri Şeker',p:22},{s:'KFEIN',n:'Kafein Yazılım',p:35},
  {s:'KGYO',n:'Kiler GYO',p:3},{s:'KLNMA',n:'Kalkınma Bank',p:22},{s:'KLSYN',n:'Kolanya San',p:3},
  {s:'KMPUR',n:'Kampür Madencilik',p:3},{s:'KONYA',n:'Konya Çimento',p:55},{s:'KOPOL',n:'Koza Polyester',p:8},
  {s:'KRDMA',n:'KARDEMİR A',p:18},{s:'KRDMB',n:'KARDEMİR B',p:18},{s:'KRSTL',n:'Kristal Kola',p:22},
  {s:'KUTPO',n:'Kütahya Porselen',p:22},{s:'LIDFA',n:'Lider Faktoring',p:3},{s:'LINK',n:'Link Bilgisayar',p:5},
  {s:'LKMNH',n:'Lokman Hekim',p:35},{s:'LUKSK',n:'Lüks Kadife',p:12},{s:'MAALT',n:'Marmara Altın',p:3},
  {s:'MAKIM',n:'Makina Takım',p:12},{s:'MANAS',n:'Manas Enerji',p:5},{s:'MEPET',n:'Mepet Petrol',p:5},
  {s:'MERCN',n:'Mercan Kimya',p:8},{s:'MIATK',n:'Mia Teknoloji',p:5},{s:'MNDRS',n:'Menderes Tekstil',p:8},
  {s:'MOBTL',n:'Mobiltel',p:3},{s:'MOGAN',n:'Moğan Enerji',p:5},{s:'MRSHL',n:'Marshall',p:42},
  {s:'MSGYO',n:'Metro GYO',p:3},{s:'MTRYO',n:'Metro Yatırım',p:3},{s:'NATEN',n:'Naturel Enerji',p:5},
  {s:'NTGAZ',n:'NTG Doğalgaz',p:12},{s:'NUGYO',n:'Nurol GYO',p:8},{s:'OBAMS',n:'Oba Makarna',p:12},
  {s:'OBASE',n:'Obase Bilgisayar',p:3},{s:'OFSYM',n:'Ofsay Seymen',p:5},{s:'ONCSM',n:'Onko Sağlık',p:5},
  {s:'ORCAY',n:'Orçay',p:5},{s:'OSMEN',n:'Osmaniye Çimento',p:18},{s:'OYLUM',n:'Oylum Sınai',p:3},
  {s:'OZGYO',n:'Özderici GYO',p:3},{s:'OZRDN',n:'Özerden',p:8},{s:'OZTK',n:'Öztürk Holding',p:3},
  {s:'PAMEL',n:'Pamel Yenilenebilir',p:12},{s:'PCILT',n:'PC İletişim',p:3},{s:'PENGD',n:'Penguen Gıda',p:3},
  {s:'PETUN',n:'Pınar Et',p:42},{s:'PINSU',n:'Pınar Su',p:22},{s:'PKART',n:'Plastikkart',p:12},
  {s:'PKENT',n:'Park Elektrik',p:12},{s:'PLTUR',n:'Platform Turizm',p:3},{s:'PNLSN',n:'Panel Sanayi',p:3},
  {s:'PNSUT',n:'Pınar Süt',p:75},{s:'PRZMA',n:'Prizma Pres',p:3},{s:'PSGYO',n:'Pera GYO',p:3},
  {s:'QNBFL',n:'QNB Fin. Kiralama',p:12},{s:'RALYH',n:'Rally Holding',p:3},{s:'RAYSG',n:'Ray Sigorta',p:8},
  {s:'RGYAS',n:'Reysaş GYO',p:3},{s:'RODRG',n:'Rodrigo Tekstil',p:3},{s:'ROYAL',n:'Royal Halı',p:18},
  {s:'RUBNS',n:'Rubenis Tekstil',p:3},{s:'SAMAT',n:'Saray Matbaacılık',p:3},{s:'SANEL',n:'Sanel Mühendislik',p:3},
  {s:'SANKO',n:'Sanko Pazarlama',p:5},{s:'SAYAS',n:'Say Reklamcılık',p:3},{s:'SDTTR',n:'SDT Uzay',p:22},
  {s:'SEGYO',n:'Sera GYO',p:3},{s:'SEKFK',n:'Şeker Fin. Kiralama',p:5},{s:'SELGD',n:'Selçuk Gıda',p:5},
  {s:'SILVR',n:'Silver Gümüş',p:5},{s:'SNPAM',n:'Sınai Ambalaj',p:3},{s:'SODSN',n:'Sodaş Sodyum',p:5},
  {s:'SOKE',n:'Söke Çimento',p:22},{s:'SONME',n:'Sonmez Pamuklu',p:5},{s:'SRVGY',n:'Servet GYO',p:3},
  {s:'TBORG',n:'T. Tuborg',p:95},{s:'TGSAS',n:'TGS Dış Ticaret',p:8},{s:'TKNSA',n:'Teknosa',p:18},
  {s:'TLMAN',n:'Tilman İlaç',p:5},{s:'TMPOL',n:'Temapol Polimer',p:3},{s:'TUCLK',n:'Tuğçelik',p:18},
  {s:'UFUK',n:'Ufuk Yatırım',p:3},{s:'USAK',n:'Uşak Seramik',p:5},{s:'UZERB',n:'Üzümcü Erbil',p:3},
  {s:'VANGD',n:'Vanet Gıda',p:5},{s:'VBTYZ',n:'VBT Yazılım',p:8},{s:'VKGYO',n:'Vakıf Konut GYO',p:3},
  {s:'YAPRK',n:'Yaprak Süt',p:3},{s:'YAYLA',n:'Yayla Agro',p:18},{s:'YATAS',n:'Yataş',p:42},
  {s:'YGYO',n:'Yeşil GYO',p:3},{s:'YKSLN',n:'Yüksel İnşaat',p:5},{s:'YBTAS',n:'Yibitaş',p:5},
  {s:'ZEDUR',n:'Zedur Enerji',p:3},{s:'ZELOT',n:'Zelo Teknoloji',p:3},{s:'AKSGY',n:'Akiş GYO',p:5},
  {s:'ALTNY',n:'Altınay Savunma',p:42},{s:'ALVES',n:'Alves Kablo',p:5},{s:'ARTMS',n:'Artemis Halı',p:5},
  {s:'ATATP',n:'ATP Bilgisayar',p:3},{s:'BALAT',n:'Balatacilar',p:12},{s:'BAYRK',n:'Bayrak Taban',p:3},
  {s:'BURVA',n:'Burgan Varlık',p:3},{s:'CMENT',n:'Çiment Müstahsilleri',p:3},{s:'DAGI',n:'Dagi Giyim',p:18},
  {s:'DERIM',n:'Derimod',p:14},{s:'DOKTA',n:'Doktaş',p:8},{s:'DURDO',n:'Duran Doğan',p:18},
  {s:'DZGYO',n:'Deniz GYO',p:3},{s:'EMKEL',n:'Emkel',p:3},{s:'ERSU',n:'Ersu Meyve',p:8},
  {s:'GEDZA',n:'Gediz Ambalaj',p:5},{s:'GRNYO',n:'Garanti GYO',p:3},{s:'HATSN',n:'Hatsan',p:120},
  {s:'HURGZ',n:'Hürriyet',p:3},{s:'IHEVA',n:'İhlas Ev Aletleri',p:3},{s:'ISKPL',n:'İskenderun B',p:3},
  {s:'ISBIR',n:'İşbir Sentetik',p:38},{s:'KENT',n:'Kent Gıda',p:180},{s:'KRTEK',n:'Kartonsan',p:280},
  {s:'KUYAS',n:'Kuyumcukent',p:3},{s:'MNDRS',n:'Menderes Tekstil',p:8},{s:'NTGAZ',n:'NTG Doğalgaz',p:12},
  {s:'OYLUM',n:'Oylum',p:3},{s:'PNSUT',n:'Pınar Süt',p:75},{s:'RYGYO',n:'Reysaş GYO',p:3},
  {s:'SELEC',n:'Selçuk Ecza',p:58},{s:'SNKRN',n:'Senkron Siber',p:8},{s:'TGSAS',n:'TGS Dış Ticaret',p:8},
  {s:'TMPOL',n:'Temapol',p:3},{s:'UFUK',n:'Ufuk Yat',p:3},{s:'YATAS',n:'Yataş',p:42},
  {s:'YBTAS',n:'Yibitaş',p:5},{s:'PRKME',n:'Park Elek. Madencilik',p:42},{s:'MTRKS',n:'Matreks Bilişim',p:12},
  {s:'OFSYM',n:'Ofsay',p:5},{s:'KAYSE',n:'Kayseri Şeker',p:22},{s:'ACSEL',n:'Acıselsan Acıpayam',p:145},
  {s:'ADESE',n:'Adese AVM',p:5},{s:'AGYO',n:'Atakule GYO',p:3},{s:'AKCNS',n:'Akçansa',p:85},
  {s:'AKENR',n:'Ak Enerji',p:12},{s:'ALKIM',n:'Alkim Kimya',p:22},{s:'ALCAR',n:'Alarko Carrier',p:65},
  {s:'ARMDA',n:'Armada',p:8},{s:'AVTUR',n:'Avrasya Petrol',p:5},{s:'AYDEM',n:'Aydem Enerji',p:12},
  {s:'BASGZ',n:'Başgazete',p:5},{s:'BINHO',n:'Bin Holding',p:5},{s:'BIOEN',n:'Biotrend',p:8},
  {s:'BMSTL',n:'BMS Birleşik',p:8},{s:'CANTE',n:'Çan Termik',p:5},{s:'CVKMD',n:'CVK Madencilik',p:5},
  {s:'DENGE',n:'Denge Holding',p:3},{s:'EDATA',n:'E-Data',p:3},{s:'ENSRI',n:'Enerjisa Üretim',p:5},
  {s:'EUPWR',n:'Euro Power',p:3},{s:'GARFA',n:'Gar Finans',p:5},{s:'GEDIK',n:'Gedik Yatırım',p:3},
  {s:'GENIL',n:'Genişletilmiş İleri',p:3},{s:'GLCVY',n:'Gelecek Varlık',p:3},{s:'GRNYO',n:'Garanti GYO',p:3}
];

export const NASDAQ_SYMBOLS: SymbolInfo[] = [
  {s:'AAPL',n:'Apple Inc.',p:185},{s:'MSFT',n:'Microsoft',p:420},{s:'GOOGL',n:'Alphabet A',p:175},
  {s:'AMZN',n:'Amazon',p:180},{s:'NVDA',n:'NVIDIA',p:890},{s:'META',n:'Meta Platforms',p:485},
  {s:'TSLA',n:'Tesla',p:175},{s:'BRK-B',n:'Berkshire Hathaway B',p:410},{s:'UNH',n:'UnitedHealth',p:520},
  {s:'JNJ',n:'Johnson & Johnson',p:155},{s:'V',n:'Visa',p:285},{s:'XOM',n:'Exxon Mobil',p:105},
  {s:'WMT',n:'Walmart',p:165},{s:'JPM',n:'JPMorgan Chase',p:195},{s:'PG',n:'Procter & Gamble',p:160},
  {s:'MA',n:'Mastercard',p:470},{s:'HD',n:'Home Depot',p:385},{s:'CVX',n:'Chevron',p:155},
  {s:'MRK',n:'Merck',p:125},{s:'ABBV',n:'AbbVie',p:175},{s:'LLY',n:'Eli Lilly',p:785},
  {s:'PFE',n:'Pfizer',p:28},{s:'KO',n:'Coca-Cola',p:62},{s:'PEP',n:'PepsiCo',p:175},
  {s:'COST',n:'Costco',p:720},{s:'TMO',n:'Thermo Fisher',p:580},{s:'AVGO',n:'Broadcom',p:1350},
  {s:'MCD',n:'McDonald\'s',p:295},{s:'CSCO',n:'Cisco',p:50},{s:'ACN',n:'Accenture',p:350},
  {s:'ABT',n:'Abbott Labs',p:108},{s:'NKE',n:'Nike',p:95},{s:'TXN',n:'Texas Instruments',p:172},
  {s:'DHR',n:'Danaher',p:250},{s:'CRM',n:'Salesforce',p:300},{s:'NEE',n:'NextEra Energy',p:62},
  {s:'UPS',n:'United Parcel Service',p:145},{s:'MS',n:'Morgan Stanley',p:95},{s:'BMY',n:'Bristol-Myers',p:52},
  {s:'RTX',n:'RTX Corp',p:95},{s:'LOW',n:'Lowe\'s',p:240},{s:'SCHW',n:'Charles Schwab',p:72},
  {s:'HON',n:'Honeywell',p:205},{s:'IBM',n:'IBM',p:190},{s:'AMGN',n:'Amgen',p:285},
  {s:'DE',n:'Deere & Co',p:395},{s:'GS',n:'Goldman Sachs',p:445},{s:'CAT',n:'Caterpillar',p:295},
  {s:'INTU',n:'Intuit',p:630},{s:'BLK',n:'BlackRock',p:785},{s:'SYK',n:'Stryker',p:340},
  {s:'MDLZ',n:'Mondelez',p:72},{s:'ADP',n:'ADP',p:245},{s:'GILD',n:'Gilead Sciences',p:78},
  {s:'CI',n:'Cigna Group',p:340},{s:'ADI',n:'Analog Devices',p:195},{s:'ISRG',n:'Intuitive Surgical',p:395},
  {s:'CB',n:'Chubb',p:255},{s:'LMT',n:'Lockheed Martin',p:465},{s:'PYPL',n:'PayPal',p:68},
  {s:'ZTS',n:'Zoetis',p:175},{s:'CVS',n:'CVS Health',p:75},{s:'REGN',n:'Regeneron',p:945},
  {s:'GE',n:'General Electric',p:155},{s:'AMT',n:'American Tower',p:195},{s:'SLB',n:'Schlumberger',p:48},
  {s:'VRTX',n:'Vertex Pharma',p:420},{s:'FISV',n:'Fiserv',p:145},{s:'MO',n:'Altria',p:42},
  {s:'EOG',n:'EOG Resources',p:118},{s:'SO',n:'Southern Co',p:72},{s:'CL',n:'Colgate-Palmolive',p:82},
  {s:'ITW',n:'Illinois Tool Works',p:250},{s:'CME',n:'CME Group',p:210},{s:'EQIX',n:'Equinix',p:815},
  {s:'CSX',n:'CSX Corp',p:35},{s:'SNPS',n:'Synopsys',p:530},{s:'BDX',n:'Becton Dickinson',p:240},
  {s:'AON',n:'Aon',p:340},{s:'PGR',n:'Progressive',p:185},{s:'BSX',n:'Boston Scientific',p:72},
  {s:'CCI',n:'Crown Castle',p:105},{s:'PLD',n:'Prologis',p:118},{s:'NOC',n:'Northrop Grumman',p:475},
  {s:'WM',n:'Waste Management',p:195},{s:'ICE',n:'ICE',p:130},{s:'CDNS',n:'Cadence Design',p:280},
  {s:'FIS',n:'Fidelity National',p:68},{s:'APD',n:'Air Products',p:280},{s:'TGT',n:'Target',p:142},
  {s:'DG',n:'Dollar General',p:125},{s:'MCK',n:'McKesson',p:510},{s:'ORLY',n:'O\'Reilly Auto',p:945},
  {s:'SHW',n:'Sherwin-Williams',p:320},{s:'KLAC',n:'KLA Corp',p:620},{s:'HUM',n:'Humana',p:370},
  {s:'AEP',n:'American Electric',p:88},{s:'PSA',n:'Public Storage',p:285},{s:'EL',n:'Estée Lauder',p:145},
  {s:'MNST',n:'Monster Beverage',p:55},{s:'APH',n:'Amphenol',p:98},{s:'EMR',n:'Emerson Electric',p:100},
  {s:'MCHP',n:'Microchip Tech',p:82},{s:'GIS',n:'General Mills',p:68},{s:'KMB',n:'Kimberly-Clark',p:128},
  {s:'ECL',n:'Ecolab',p:195},{s:'WELL',n:'Welltower',p:92},{s:'MAR',n:'Marriott',p:240},
  {s:'MSCI',n:'MSCI Inc',p:545},{s:'CTSH',n:'Cognizant',p:72},{s:'NXPI',n:'NXP Semi',p:225},
  {s:'AZO',n:'AutoZone',p:2780},{s:'DLTR',n:'Dollar Tree',p:135},{s:'PH',n:'Parker-Hannifin',p:445},
  {s:'SRE',n:'Sempra',p:75},{s:'ROP',n:'Roper Tech',p:545},{s:'NEM',n:'Newmont',p:42},
  {s:'CTAS',n:'Cintas',p:580},{s:'IQV',n:'IQVIA',p:225},{s:'CMG',n:'Chipotle',p:2850},
  {s:'STZ',n:'Constellation Brands',p:245},{s:'PSX',n:'Phillips 66',p:125},{s:'ADSK',n:'Autodesk',p:225},
  {s:'IDXX',n:'IDEXX Labs',p:540},{s:'FTNT',n:'Fortinet',p:62},{s:'TRV',n:'Travelers',p:195},
  {s:'MPC',n:'Marathon Petroleum',p:155},{s:'HSY',n:'Hershey',p:195},{s:'PCAR',n:'PACCAR',p:92},
  {s:'AIG',n:'AIG',p:72},{s:'CARR',n:'Carrier Global',p:58},{s:'AFL',n:'Aflac',p:82},
  {s:'OXY',n:'Occidental Petroleum',p:58},{s:'HCA',n:'HCA Healthcare',p:285},{s:'PAYX',n:'Paychex',p:125},
  {s:'FAST',n:'Fastenal',p:62},{s:'PCG',n:'PG&E Corp',p:18},{s:'KHC',n:'Kraft Heinz',p:35},
  {s:'KDP',n:'Keurig Dr Pepper',p:32},{s:'YUM',n:'Yum! Brands',p:135},{s:'EW',n:'Edwards Lifesciences',p:75},
  {s:'F',n:'Ford Motor',p:12},{s:'GM',n:'General Motors',p:38},{s:'D',n:'Dominion Energy',p:48},
  {s:'DUK',n:'Duke Energy',p:98},{s:'ED',n:'Consolidated Edison',p:95},{s:'EXC',n:'Exelon',p:42},
  {s:'ES',n:'Eversource Energy',p:62},{s:'FE',n:'FirstEnergy',p:38},{s:'PPL',n:'PPL Corp',p:28},
  {s:'WEC',n:'WEC Energy',p:88},{s:'XEL',n:'Xcel Energy',p:62},{s:'AES',n:'AES Corp',p:18},
  {s:'CMS',n:'CMS Energy',p:62},{s:'EVRG',n:'Evergy',p:52},{s:'LNT',n:'Alliant Energy',p:52},
  {s:'NI',n:'NiSource',p:28},{s:'PNW',n:'Pinnacle West',p:78},{s:'NRG',n:'NRG Energy',p:55},
  {s:'GOOG',n:'Alphabet C',p:177},{s:'AMD',n:'AMD',p:170},{s:'NFLX',n:'Netflix',p:620},
  {s:'INTC',n:'Intel',p:30},{s:'COIN',n:'Coinbase',p:250},{s:'PLTR',n:'Palantir',p:24},
  {s:'MSTR',n:'MicroStrategy',p:1500},{s:'HOOD',n:'Robinhood',p:18},{s:'SQ',n:'Block Inc',p:72},
  {s:'SHOP',n:'Shopify',p:78},{s:'SNAP',n:'Snap Inc',p:12},{s:'UBER',n:'Uber',p:72},
  {s:'LYFT',n:'Lyft',p:15},{s:'ABNB',n:'Airbnb',p:145},{s:'RBLX',n:'Roblox',p:42},
  {s:'RIVN',n:'Rivian',p:18},{s:'LCID',n:'Lucid Group',p:4},{s:'NIO',n:'NIO Inc',p:5},
  {s:'SOFI',n:'SoFi Technologies',p:8},{s:'DKNG',n:'DraftKings',p:38},{s:'ROKU',n:'Roku',p:62},
  {s:'CRWD',n:'CrowdStrike',p:295},{s:'ZS',n:'Zscaler',p:195},{s:'PANW',n:'Palo Alto Networks',p:295},
  {s:'DDOG',n:'Datadog',p:115},{s:'NET',n:'Cloudflare',p:82},{s:'SNOW',n:'Snowflake',p:165},
  {s:'MDB',n:'MongoDB',p:380},{s:'TEAM',n:'Atlassian',p:225},{s:'WDAY',n:'Workday',p:255},
  {s:'OKTA',n:'Okta',p:95},{s:'TWLO',n:'Twilio',p:62},{s:'U',n:'Unity Software',p:28},
  {s:'PATH',n:'UiPath',p:18},{s:'BILL',n:'Bill.com',p:72},{s:'HUBS',n:'HubSpot',p:545},
  {s:'TTD',n:'Trade Desk',p:82},{s:'ZM',n:'Zoom Video',p:68},{s:'DOCU',n:'DocuSign',p:55},
  {s:'PINS',n:'Pinterest',p:32},{s:'ETSY',n:'Etsy',p:72},{s:'SPOT',n:'Spotify',p:195},
  {s:'SE',n:'Sea Limited',p:42},{s:'MELI',n:'MercadoLibre',p:1650},{s:'BABA',n:'Alibaba',p:72},
  {s:'JD',n:'JD.com',p:28},{s:'PDD',n:'PDD Holdings',p:125},{s:'BIDU',n:'Baidu',p:105},
  {s:'TCEHY',n:'Tencent ADR',p:42},{s:'TME',n:'Tencent Music',p:8},{s:'BILI',n:'Bilibili',p:12},
  {s:'LI',n:'Li Auto',p:28},{s:'XPEV',n:'XPeng',p:8},{s:'WB',n:'Weibo',p:10},
  {s:'FUTU',n:'Futu Holdings',p:55},{s:'TIGR',n:'Tiger Brokers',p:5},{s:'ZIM',n:'ZIM Shipping',p:12},
  {s:'DAL',n:'Delta Air Lines',p:42},{s:'UAL',n:'United Airlines',p:48},{s:'AAL',n:'American Airlines',p:14},
  {s:'LUV',n:'Southwest Airlines',p:28},{s:'BA',n:'Boeing',p:210},{s:'GD',n:'General Dynamics',p:265},
  {s:'LHX',n:'L3Harris',p:210},{s:'TDG',n:'TransDigm',p:1150},{s:'HWM',n:'Howmet Aerospace',p:52},
  {s:'TXT',n:'Textron',p:82},{s:'SPR',n:'Spirit AeroSystems',p:28},{s:'ERJ',n:'Embraer',p:18},
  {s:'CPA',n:'Copa Holdings',p:95},{s:'JBLU',n:'JetBlue',p:5},{s:'ALK',n:'Alaska Air',p:38},
  {s:'HA',n:'Hawaiian Holdings',p:14},{s:'SAVE',n:'Spirit Airlines',p:5},{s:'SKYW',n:'SkyWest',p:55},
  {s:'DIS',n:'Walt Disney',p:95},{s:'CMCSA',n:'Comcast',p:42},{s:'T',n:'AT&T',p:17},
  {s:'VZ',n:'Verizon',p:38},{s:'TMUS',n:'T-Mobile US',p:165},{s:'CHTR',n:'Charter Comm',p:355},
  {s:'PARA',n:'Paramount',p:12},{s:'WBD',n:'Warner Bros Discovery',p:8},{s:'FOX',n:'Fox Corp',p:32},
  {s:'NWSA',n:'News Corp',p:25},{s:'VIAC',n:'ViacomCBS',p:12},{s:'IPG',n:'Interpublic',p:32},
  {s:'OMC',n:'Omnicom',p:82},{s:'LYV',n:'Live Nation',p:95},{s:'MTCH',n:'Match Group',p:35},
  {s:'EA',n:'Electronic Arts',p:135},{s:'TTWO',n:'Take-Two',p:155},{s:'ATVI',n:'Activision',p:82},
  {s:'WMG',n:'Warner Music',p:32},{s:'LUMN',n:'Lumen Tech',p:2},{s:'DISH',n:'DISH Network',p:5},
  {s:'WFC',n:'Wells Fargo',p:52},{s:'BAC',n:'Bank of America',p:35},{s:'C',n:'Citigroup',p:52},
  {s:'USB',n:'US Bancorp',p:42},{s:'PNC',n:'PNC Financial',p:155},{s:'TFC',n:'Truist Financial',p:35},
  {s:'COF',n:'Capital One',p:135},{s:'BK',n:'Bank of New York',p:52},{s:'STT',n:'State Street',p:78},
  {s:'FITB',n:'Fifth Third',p:32},{s:'HBAN',n:'Huntington Banc',p:12},{s:'KEY',n:'KeyCorp',p:14},
  {s:'RF',n:'Regions Financial',p:18},{s:'CFG',n:'Citizens Financial',p:32},{s:'MTB',n:'M&T Bank',p:142},
  {s:'SIVB',n:'SVB Financial',p:235},{s:'ZION',n:'Zions Banc',p:42},{s:'CMA',n:'Comerica',p:52},
  {s:'FRC',n:'First Republic',p:115},{s:'ALLY',n:'Ally Financial',p:28},{s:'SOFI',n:'SoFi',p:8},
  {s:'AXP',n:'American Express',p:185},{s:'DFS',n:'Discover Financial',p:115},{s:'SYF',n:'Synchrony',p:35},
  {s:'NDAQ',n:'Nasdaq Inc',p:62},{s:'SPGI',n:'S&P Global',p:435},{s:'MCO',n:'Moody\'s',p:385},
  {s:'MSCI',n:'MSCI',p:545},{s:'FDS',n:'FactSet',p:445},{s:'MKTX',n:'MarketAxess',p:245},
  {s:'CBOE',n:'Cboe Global',p:175},{s:'TW',n:'Tradeweb',p:95},{s:'VIRT',n:'Virtu Financial',p:18},
  {s:'IBKR',n:'Interactive Brokers',p:92},{s:'LPLA',n:'LPL Financial',p:235},{s:'RJF',n:'Raymond James',p:108},
  {s:'EVR',n:'Evercore',p:165},{s:'HLI',n:'Houlihan Lokey',p:115},{s:'PJT',n:'PJT Partners',p:85},
  {s:'BX',n:'Blackstone',p:125},{s:'KKR',n:'KKR & Co',p:95},{s:'APO',n:'Apollo Global',p:92},
  {s:'CG',n:'Carlyle Group',p:38},{s:'ARES',n:'Ares Management',p:105},{s:'OWL',n:'Blue Owl',p:14},
  {s:'TPG',n:'TPG Inc',p:38},{s:'TROW',n:'T Rowe Price',p:108},{s:'IVZ',n:'Invesco',p:18},
  {s:'BEN',n:'Franklin Resources',p:28},{s:'AMG',n:'Affiliated Managers',p:155},{s:'VCIT',n:'Vanguard Corp',p:82},
  {s:'MMM',n:'3M Company',p:105},{s:'GE',n:'GE Aerospace',p:155},{s:'HON',n:'Honeywell',p:205},
  {s:'ETN',n:'Eaton Corp',p:235},{s:'EMR',n:'Emerson',p:100},{s:'ROK',n:'Rockwell Auto',p:280},
  {s:'OTIS',n:'Otis Worldwide',p:88},{s:'GWW',n:'W.W. Grainger',p:885},{s:'SWK',n:'Stanley B&D',p:85},
  {s:'RHI',n:'Robert Half',p:72},{s:'CPRT',n:'Copart',p:48},{s:'POOL',n:'Pool Corp',p:355},
  {s:'WSO',n:'Watsco',p:395},{s:'LIN',n:'Linde',p:425},{s:'FCX',n:'Freeport-McMoRan',p:42},
  {s:'DOW',n:'Dow Inc',p:55},{s:'DD',n:'DuPont',p:72},{s:'PPG',n:'PPG Industries',p:135},
  {s:'ALB',n:'Albemarle',p:125},{s:'CE',n:'Celanese',p:135},{s:'EMN',n:'Eastman Chemical',p:82},
  {s:'HUN',n:'Huntsman',p:25},{s:'SMG',n:'Scotts Miracle',p:58},{s:'FMC',n:'FMC Corp',p:62},
  {s:'IFF',n:'Intl Flavors',p:78},{s:'MTD',n:'Mettler-Toledo',p:1280},{s:'PKG',n:'Packaging Corp',p:175},
  {s:'IP',n:'International Paper',p:35},{s:'SEE',n:'Sealed Air',p:35},{s:'BLL',n:'Ball Corp',p:55},
  {s:'AVY',n:'Avery Dennison',p:195},{s:'AMCR',n:'Amcor',p:9},{s:'CLX',n:'Clorox',p:145},
  {s:'CHD',n:'Church & Dwight',p:98},{s:'SJM',n:'JM Smucker',p:125},{s:'MKC',n:'McCormick',p:72},
  {s:'HRL',n:'Hormel Foods',p:32},{s:'CPB',n:'Campbell Soup',p:42},{s:'CAG',n:'Conagra',p:28},
  {s:'K',n:'Kellanova',p:58},{s:'TSN',n:'Tyson Foods',p:52},{s:'BG',n:'Bunge',p:95},
  {s:'ADM',n:'Archer-Daniels',p:72},{s:'DXCM',n:'DexCom',p:115},{s:'ALGN',n:'Align Tech',p:285},
  {s:'HOLX',n:'Hologic',p:72},{s:'ILMN',n:'Illumina',p:125},{s:'A',n:'Agilent Tech',p:135},
  {s:'WAT',n:'Waters Corp',p:285},{s:'TER',n:'Teradyne',p:98},{s:'KEYS',n:'Keysight',p:145},
  {s:'TRMB',n:'Trimble',p:55},{s:'ZBRA',n:'Zebra Tech',p:285},{s:'TECH',n:'Bio-Techne',p:72},
  {s:'BIO',n:'Bio-Rad Labs',p:345},{s:'PKI',n:'PerkinElmer',p:115},{s:'EFX',n:'Equifax',p:245},
  {s:'VRSK',n:'Verisk Analytics',p:240},{s:'BR',n:'Broadridge Fin',p:195},{s:'JKHY',n:'Jack Henry',p:162},
  {s:'GPN',n:'Global Payments',p:105},{s:'WEX',n:'WEX Inc',p:195},{s:'SSNC',n:'SS&C Tech',p:58},
  {s:'FLT',n:'FLEETCOR',p:270},{s:'FOUR',n:'Shift4 Payments',p:62},{s:'RPAY',n:'Repay Holdings',p:8},
  {s:'DT',n:'Dynatrace',p:48},{s:'ESTC',n:'Elastic',p:95},{s:'SPLK',n:'Splunk',p:145},
  {s:'NOW',n:'ServiceNow',p:715},{s:'VEEV',n:'Veeva Systems',p:195},{s:'COUP',n:'Coupa Software',p:78},
  {s:'PCTY',n:'Paylocity',p:155},{s:'PAYC',n:'Paycom',p:185},{s:'WK',n:'Workiva',p:95},
  {s:'MANH',n:'Manhattan Assoc',p:195},{s:'ANSS',n:'ANSYS',p:325},{s:'PTC',n:'PTC Inc',p:155},
  {s:'FICO',n:'Fair Isaac',p:1250},{s:'SMAR',n:'Smartsheet',p:42},{s:'MNDY',n:'monday.com',p:185},
  {s:'FROG',n:'JFrog',p:28},{s:'CFLT',n:'Confluent',p:28},{s:'GTLB',n:'GitLab',p:55},
  {s:'APP',n:'AppLovin',p:42},{s:'IS',n:'ironSource',p:8},{s:'MGNI',n:'Magnite',p:12},
  {s:'PUBM',n:'PubMatic',p:18},{s:'DSP',n:'Viant Tech',p:8},{s:'APPS',n:'Digital Turbine',p:5},
  {s:'AI',n:'C3.ai',p:28},{s:'BBAI',n:'BigBear.ai',p:3},{s:'SOUN',n:'SoundHound',p:5},
  {s:'PLTR',n:'Palantir',p:24},{s:'IONQ',n:'IonQ',p:12},{s:'RGTI',n:'Rigetti',p:2},
  {s:'QUBT',n:'Quantum Computing',p:3},{s:'ARQQ',n:'Arqit Quantum',p:3},{s:'LASR',n:'nLIGHT',p:12},
  {s:'ON',n:'ON Semi',p:75},{s:'MRVL',n:'Marvell Tech',p:65},{s:'SWKS',n:'Skyworks',p:95},
  {s:'QRVO',n:'Qorvo',p:98},{s:'MPWR',n:'Monolithic Power',p:545},{s:'SMCI',n:'Super Micro',p:285},
  {s:'ARM',n:'ARM Holdings',p:125},{s:'ASML',n:'ASML Holding',p:695},{s:'TSM',n:'TSMC',p:105},
  {s:'LRCX',n:'Lam Research',p:695},{s:'AMAT',n:'Applied Materials',p:155},{s:'MU',n:'Micron',p:82},
  {s:'STX',n:'Seagate',p:82},{s:'WDC',n:'Western Digital',p:48},{s:'NTAP',n:'NetApp',p:88},
  {s:'PSTG',n:'Pure Storage',p:38},{s:'HPE',n:'HP Enterprise',p:18},{s:'HPQ',n:'HP Inc',p:28},
  {s:'DELL',n:'Dell Technologies',p:72},{s:'LOGI',n:'Logitech',p:72},{s:'CRSR',n:'Corsair',p:12},
  {s:'HEAR',n:'Turtle Beach',p:12},{s:'AAON',n:'AAON Inc',p:72},{s:'GNRC',n:'Generac',p:115},
  {s:'ENPH',n:'Enphase Energy',p:118},{s:'SEDG',n:'SolarEdge',p:72},{s:'FSLR',n:'First Solar',p:165},
  {s:'RUN',n:'Sunrun',p:12},{s:'NOVA',n:'Sunnova',p:8},{s:'PLUG',n:'Plug Power',p:4},
  {s:'FCEL',n:'FuelCell Energy',p:2},{s:'BE',n:'Bloom Energy',p:14},{s:'BLDP',n:'Ballard Power',p:3},
  {s:'CHPT',n:'ChargePoint',p:2},{s:'BLNK',n:'Blink Charging',p:3},{s:'EVGO',n:'EVgo',p:3},
  {s:'QS',n:'QuantumScape',p:6},{s:'SLDP',n:'Solid Power',p:2},{s:'MVST',n:'Microvast',p:2},
  {s:'STEM',n:'Stem Inc',p:3},{s:'CLSK',n:'CleanSpark',p:12},{s:'MARA',n:'Marathon Digital',p:18},
  {s:'RIOT',n:'Riot Platforms',p:12},{s:'HUT',n:'Hut 8 Mining',p:5},{s:'BTBT',n:'Bit Digital',p:4},
  {s:'CIFR',n:'Cipher Mining',p:5},{s:'IREN',n:'Iris Energy',p:8},{s:'WULF',n:'TeraWulf',p:3},
  {s:'BITF',n:'Bitfarms',p:2},{s:'CORZ',n:'Core Scientific',p:5},{s:'ARBK',n:'Argo Blockchain',p:1},
  {s:'SQ',n:'Block',p:72},{s:'AFRM',n:'Affirm',p:28},{s:'UPST',n:'Upstart',p:28},
  {s:'LC',n:'LendingClub',p:8},{s:'OPEN',n:'Opendoor',p:3},{s:'RDFN',n:'Redfin',p:8},
  {s:'Z',n:'Zillow',p:48},{s:'ZG',n:'Zillow Group',p:48},{s:'TRUP',n:'Trupanion',p:28},
  {s:'LMND',n:'Lemonade',p:15},{s:'ROOT',n:'Root Inc',p:8},{s:'OSCR',n:'Oscar Health',p:8},
  {s:'CLOV',n:'Clover Health',p:1},{s:'HIMS',n:'Hims & Hers',p:12},{s:'DOCS',n:'Doximity',p:25},
  {s:'TDOC',n:'Teladoc',p:18},{s:'AMWL',n:'Amwell',p:3},{s:'GDRX',n:'GoodRx',p:5},
  {s:'SDGR',n:'Schrodinger',p:28},{s:'RXRX',n:'Recursion Pharma',p:8},{s:'DNA',n:'Ginkgo Bioworks',p:1},
  {s:'CRSP',n:'CRISPR Therapeutics',p:55},{s:'EDIT',n:'Editas Medicine',p:8},{s:'NTLA',n:'Intellia',p:28},
  {s:'BEAM',n:'Beam Therapeutics',p:25},{s:'VERV',n:'Verve Therapeutics',p:12},{s:'VIR',n:'Vir Biotech',p:10},
  {s:'MRNA',n:'Moderna',p:95},{s:'BNTX',n:'BioNTech',p:95},{s:'AZN',n:'AstraZeneca',p:65},
  {s:'NVO',n:'Novo Nordisk',p:125},{s:'SNY',n:'Sanofi',p:45},{s:'GSK',n:'GSK plc',p:38},
  {s:'NVS',n:'Novartis',p:95},{s:'BMY',n:'Bristol-Myers',p:52},{s:'BIIB',n:'Biogen',p:235},
  {s:'VRTX',n:'Vertex',p:420},{s:'ALNY',n:'Alnylam',p:185},{s:'SRPT',n:'Sarepta',p:115},
  {s:'EXAS',n:'Exact Sciences',p:65},{s:'GH',n:'Guardant Health',p:28},{s:'NVST',n:'Envista',p:18},
  {s:'XRAY',n:'Dentsply Sirona',p:35},{s:'HSIC',n:'Henry Schein',p:72},{s:'COO',n:'CooperCompanies',p:345},
  {s:'BDX',n:'Becton',p:240},{s:'BAX',n:'Baxter',p:38},{s:'MDT',n:'Medtronic',p:82},
  {s:'ABT',n:'Abbott',p:108},{s:'STE',n:'STERIS',p:225},{s:'RMD',n:'ResMed',p:195},
  {s:'TFX',n:'Teleflex',p:225},{s:'PODD',n:'Insulet',p:175},{s:'IRTC',n:'iRhythm',p:95},
  {s:'LIVN',n:'LivaNova',p:55},{s:'GMED',n:'Globus Medical',p:52},{s:'NUVA',n:'NuVasive',p:42},
  {s:'INSP',n:'Inspire Medical',p:195},{s:'NVCR',n:'NovoCure',p:18},{s:'AXNX',n:'Axonics',p:58},
  {s:'OTRK',n:'Ontrak',p:2},{s:'TALK',n:'Talkspace',p:3},{s:'AMZN',n:'Amazon',p:180},
  {s:'BKNG',n:'Booking Holdings',p:3550},{s:'EXPE',n:'Expedia',p:135},{s:'TRIP',n:'TripAdvisor',p:18},
  {s:'MMYT',n:'MakeMyTrip',p:45},{s:'SABR',n:'Sabre Corp',p:4},{s:'TRVG',n:'trivago',p:2},
  {s:'DASH',n:'DoorDash',p:95},{s:'GRAB',n:'Grab Holdings',p:3},{s:'CPNG',n:'Coupang',p:18},
  {s:'W',n:'Wayfair',p:48},{s:'CHWY',n:'Chewy',p:18},{s:'WISH',n:'ContextLogic',p:1},
  {s:'MNST',n:'Monster',p:55},{s:'STZ',n:'Constellation',p:245},{s:'BUD',n:'AB InBev',p:58},
  {s:'TAP',n:'Molson Coors',p:62},{s:'SAM',n:'Boston Beer',p:315},{s:'FIZZ',n:'National Bev',p:48},
  {s:'CELH',n:'Celsius',p:55},{s:'COKE',n:'Coca-Cola Consol',p:885},{s:'SBUX',n:'Starbucks',p:95},
  {s:'CMG',n:'Chipotle',p:2850},{s:'MCD',n:'McDonald\'s',p:295},{s:'DPZ',n:'Domino\'s',p:445},
  {s:'WEN',n:'Wendy\'s',p:18},{s:'QSR',n:'Restaurant Brands',p:72},{s:'JACK',n:'Jack in the Box',p:58},
  {s:'SHAK',n:'Shake Shack',p:72},{s:'WING',n:'Wingstop',p:245},{s:'CAVA',n:'CAVA Group',p:42},
  {s:'LULU',n:'Lululemon',p:385},{s:'GPS',n:'Gap Inc',p:22},{s:'ANF',n:'Abercrombie',p:125},
  {s:'AEO',n:'American Eagle',p:18},{s:'URBN',n:'Urban Outfitters',p:38},{s:'RL',n:'Ralph Lauren',p:155},
  {s:'PVH',n:'PVH Corp',p:85},{s:'TPR',n:'Tapestry',p:38},{s:'CPRI',n:'Capri Holdings',p:42},
  {s:'VFC',n:'VF Corp',p:15},{s:'HBI',n:'Hanesbrands',p:5},{s:'UAA',n:'Under Armour',p:8},
  {s:'ONON',n:'On Holding',p:32},{s:'BIRD',n:'Allbirds',p:1},{s:'SKX',n:'Skechers',p:55},
  {s:'DECK',n:'Deckers Outdoor',p:655},{s:'CROX',n:'Crocs',p:105},{s:'GOOS',n:'Canada Goose',p:12},
  {s:'FL',n:'Foot Locker',p:25},{s:'DKS',n:'Dick\'s Sporting',p:135},{s:'FIVE',n:'Five Below',p:155},
  {s:'OLPX',n:'Olaplex',p:2},{s:'ELF',n:'e.l.f. Beauty',p:115},{s:'COTY',n:'Coty Inc',p:10},
  {s:'ULTA',n:'Ulta Beauty',p:445},{s:'RVLV',n:'Revolve',p:18},{s:'REAL',n:'RealReal',p:2},
  {s:'POSH',n:'Poshmark',p:15},{s:'FTCH',n:'Farfetch',p:3},{s:'CART',n:'Instacart',p:25},
  {s:'SPG',n:'Simon Property',p:145},{s:'O',n:'Realty Income',p:55},{s:'VICI',n:'VICI Properties',p:32},
  {s:'DLR',n:'Digital Realty',p:135},{s:'SBAC',n:'SBA Comm',p:225},{s:'EXR',n:'Extra Space',p:145},
  {s:'MAA',n:'Mid-America Apt',p:135},{s:'AVB',n:'AvalonBay',p:195},{s:'EQR',n:'Equity Residential',p:62},
  {s:'UDR',n:'UDR Inc',p:38},{s:'CPT',n:'Camden Property',p:95},{s:'ESS',n:'Essex Property',p:245},
  {s:'HST',n:'Host Hotels',p:18},{s:'KRC',n:'Kilroy Realty',p:35},{s:'BXP',n:'BXP Inc',p:55},
  {s:'SLG',n:'SL Green',p:45},{s:'VNO',n:'Vornado Realty',p:25},{s:'MPW',n:'Medical Properties',p:5},
  {s:'OHI',n:'Omega Healthcare',p:28},{s:'PEAK',n:'Healthpeak',p:18},{s:'DOC',n:'Physicians Realty',p:12},
  {s:'GLPI',n:'Gaming & Leisure',p:48},{s:'RHP',n:'Ryman Hospitality',p:95},{s:'MGM',n:'MGM Resorts',p:42},
  {s:'WYNN',n:'Wynn Resorts',p:95},{s:'LVS',n:'Las Vegas Sands',p:48},{s:'CZR',n:'Caesars',p:42},
  {s:'DKNG',n:'DraftKings',p:38},{s:'RSI',n:'Rush Street',p:5},{s:'GENI',n:'Genius Sports',p:5},
  {s:'PENN',n:'PENN Entertainment',p:18},{s:'BALY',n:'Bally\'s',p:12},{s:'IGT',n:'IGT',p:28},
  {s:'MOS',n:'Mosaic Co',p:35},{s:'NTR',n:'Nutrien',p:52},{s:'CF',n:'CF Industries',p:78},
  {s:'CLF',n:'Cleveland-Cliffs',p:15},{s:'X',n:'United States Steel',p:32},{s:'NUE',n:'Nucor',p:155},
  {s:'STLD',n:'Steel Dynamics',p:115},{s:'RS',n:'Reliance Steel',p:285},{s:'CMC',n:'Commercial Metals',p:48},
  {s:'ATI',n:'ATI Inc',p:42},{s:'AA',n:'Alcoa',p:28},{s:'CENX',n:'Century Aluminum',p:12},
  {s:'KALU',n:'Kaiser Aluminum',p:68},{s:'ARNC',n:'Arconic',p:25},{s:'HXL',n:'Hexcel',p:62},
  {s:'WOR',n:'Worthington',p:55},{s:'RYN',n:'Rayonier',p:28},{s:'PCH',n:'PotlatchDeltic',p:42},
  {s:'WY',n:'Weyerhaeuser',p:32},{s:'CNP',n:'CenterPoint',p:28},{s:'OGE',n:'OGE Energy',p:35},
  {s:'POR',n:'Portland General',p:42},{s:'AVA',n:'Avista',p:38},{s:'NWE',n:'NorthWestern',p:52},
  {s:'MGEE',n:'MGE Energy',p:78},{s:'OGS',n:'ONE Gas',p:62},{s:'SWX',n:'Southwest Gas',p:68},
  {s:'WTRG',n:'Essential Utilities',p:38},{s:'AWK',n:'American Water',p:135},{s:'WTR',n:'Amer Water WTR',p:135},
  {s:'SUI',n:'Sun Communities',p:125},{s:'ELS',n:'Equity LifeStyle',p:68},{s:'REXR',n:'Rexford',p:48},
  {s:'FR',n:'First Industrial',p:52},{s:'STAG',n:'STAG Industrial',p:35},{s:'PNR',n:'Pentair',p:68},
  {s:'XYL',n:'Xylem',p:115},{s:'IEX',n:'IDEX Corp',p:195},{s:'MIDD',n:'Middleby',p:135},
  {s:'AOS',n:'A.O. Smith',p:72},{s:'SNA',n:'Snap-on',p:275},{s:'TTC',n:'Toro',p:85},
  {s:'MTZ',n:'MasTec',p:55},{s:'FIX',n:'Comfort Systems',p:195},{s:'EME',n:'EMCOR',p:225},
  {s:'PWR',n:'Quanta Services',p:195},{s:'APG',n:'APi Group',p:28},{s:'J',n:'Jacobs Eng',p:135},
  {s:'WSC',n:'WillScot Mobile',p:45},{s:'URI',n:'United Rentals',p:545},{s:'HEES',n:'H&E Equipment',p:42},
  {s:'HRI',n:'Herc Holdings',p:125},{s:'NSC',n:'Norfolk Southern',p:205},{s:'UNP',n:'Union Pacific',p:235},
  {s:'CNI',n:'Canadian National',p:105},{s:'CP',n:'Canadian Pacific',p:78},{s:'KSU',n:'Kansas City S',p:95},
  {s:'ODFL',n:'Old Dominion',p:395},{s:'XPO',n:'XPO Inc',p:82},{s:'SAIA',n:'Saia Inc',p:385},
  {s:'JBHT',n:'JB Hunt',p:195},{s:'KNX',n:'Knight-Swift',p:55},{s:'WERN',n:'Werner',p:38},
  {s:'SNDR',n:'Schneider',p:25},{s:'CHRW',n:'CH Robinson',p:82},{s:'EXPD',n:'Expeditors',p:118},
  {s:'MATX',n:'Matson',p:82},{s:'UBER',n:'Uber',p:72},{s:'LYFT',n:'Lyft',p:15},
  {s:'GRAB',n:'Grab',p:3},{s:'CPNG',n:'Coupang',p:18},{s:'CVS',n:'CVS',p:75}
];

export const BIST_LOGO_DOMAINS: Record<string, string> = {
  'THYAO': 'thy.com', 'GARAN': 'garantibbva.com.tr', 'AKBNK': 'akbank.com',
  'YKBNK': 'yapikredi.com.tr', 'ISCTR': 'isbank.com.tr', 'KCHOL': 'koc.com.tr',
  'SAHOL': 'sabanci.com', 'TCELL': 'turkcell.com.tr', 'BIMAS': 'bim.com.tr',
  'ASELS': 'aselsan.com.tr', 'EREGL': 'erdemir.com.tr', 'TUPRS': 'tupras.com.tr',
  'SISE': 'sisecam.com.tr', 'FROTO': 'ford.com.tr', 'TOASO': 'fiat.com.tr',
  'PGSUS': 'flypgs.com', 'ENKAI': 'enka.com', 'VESTL': 'vestel.com.tr',
  'ARCLK': 'arcelik.com.tr', 'PETKM': 'petkim.com.tr', 'SASA': 'sasa.com.tr',
  'KOZAL': 'kozamaden.com.tr', 'TAVHL': 'tavhavalimanlari.com.tr', 'TKFEN': 'tekfen.com.tr',
  'MGROS': 'migros.com.tr', 'TTKOM': 'turktelekom.com.tr', 'TTRAK': 'turktraktor.com.tr',
  'OTKAR': 'otokar.com.tr', 'AEFES': 'anadoluefes.com', 'ULKER': 'ulker.com.tr',
  'CCOLA': 'cci.com.tr', 'VAKBN': 'vakifbank.com.tr', 'HALKB': 'halkbank.com.tr',
  'MAVI': 'mavicompany.com', 'LOGO': 'logo.com.tr', 'BRISA': 'brisa.com.tr',
  'DOAS': 'dogusotomotiv.com.tr', 'EGEEN': 'egeendustri.com.tr', 'ENJSA': 'enerjisa.com.tr',
  'SOKM': 'sokmarket.com.tr', 'DEVA': 'devaholding.com.tr', 'HUBVC': 'hubvc.com',
  'HTTBT': 'hitit.com', 'CLEBI': 'celebiaviation.com', 'FENER': 'fenerbahce.org',
  'GSRAY': 'galatasaray.org', 'BJKAS': 'bjk.com.tr', 'PGSUS': 'flypgs.com',
  'GOODY': 'goodyear.com.tr', 'BMSCH': 'bosch.com.tr', 'BFREN': 'bosch.com.tr',
  'KAREL': 'karel.com.tr', 'NETAS': 'netas.com.tr', 'KORDS': 'kordsa.com',
  'MPARK': 'mlpsaglik.com.tr', 'GESAN': 'gesan.com.tr', 'CIMSA': 'cimsa.com.tr',
  'AKSEN': 'aksaenerji.com.tr', 'ZOREN': 'zorluenerji.com.tr', 'DOHOL': 'doganholding.com.tr',
  'GWIND': 'galatawind.com', 'PNSUT': 'pinar.com.tr', 'KENT': 'kentgida.com.tr',
  'HATSN': 'hatsan.com.tr', 'ASTOR': 'astor.com.tr', 'KONTR': 'kontrolmatik.com',
  'PENTA': 'pentatek.com', 'TKNSA': 'teknosa.com', 'YATAS': 'yatasbedding.com',
  'ALCAR': 'alarkocarrier.com.tr', 'BRLSM': 'birlesim.com', 'DESPC': 'despec.com',
  'ARENA': 'arenabilgisayar.com.tr', 'INDES': 'indeks.com.tr', 'KRONT': 'krontelecom.com',
  'KFEIN': 'kafein.com.tr', 'CRFSA': 'carrefoursa.com', 'BIZIM': 'bizimtoptan.com.tr',
  'BANVT': 'banvit.com', 'SUWEN': 'suwen.com.tr', 'ARZUM': 'arzum.com.tr',
  'SELEC': 'selcukecza.com.tr', 'ADEL': 'adel.com.tr', 'BAGFS': 'bagfas.com.tr',
  'AYGAZ': 'aygaz.com.tr', 'ECILC': 'eczacibasi.com.tr', 'ALBRK': 'albarakaturk.com.tr',
  'KLMSN': 'klimasan.com.tr', 'DAGI': 'dagi.com.tr', 'DERIM': 'derimod.com.tr',
  'AGESA': 'agesa.com.tr', 'AGHOL': 'agholding.com.tr', 'AKCNS': 'akcansa.com.tr',
  'AKENR': 'akenerji.com.tr', 'AKFGY': 'akfen.com.tr', 'AKFYE': 'akfen.com.tr',
  'ALARK': 'alarko.com.tr', 'ALFAS': 'alfasolar.com.tr', 'ALGYO': 'alarko.com.tr',
  'ALKIM': 'alkimkimya.com.tr', 'ALTNY': 'altinaysavunma.com', 'ANACM': 'anadolucam.com.tr',
  'ANHYT': 'anadoluhayat.com.tr', 'ANSGR': 'anadolusigorta.com.tr', 'ASUZU': 'anadoluisuzu.com.tr',
  'AYDEM': 'aydemenerji.com.tr', 'BAKAB': 'bakambalaj.com',
  'BOSSA': 'bossa.com.tr',
  'BRKSN': 'berkosan.com.tr', 'BRYAT': 'borusanyatirim.com', 'BSOKE': 'batisoke.com.tr',
  'BTCIM': 'baticimeneto.com.tr', 'BUCIM': 'burcimento.com.tr', 'CELHA': 'celikhalat.com.tr',
  'CUSAN': 'cuhadaroglu.com.tr', 'DAGHL': 'dagiletisim.com.tr',
  'DARDL': 'dardanel.com', 'DESA': 'desa.com.tr', 'DGATE': 'datagate.com.tr',
  'DITAS': 'ditas.com.tr', 'DYOBY': 'dyopaints.com', 'EGPRO': 'egeprofil.com.tr',
  'EKGYO': 'emlakkonut.com.tr', 'ERBOS': 'erbosan.com.tr', 'ESCAR': 'escar.com.tr',
  'FMIZP': 'fmizmir.com.tr', 'FRIGO': 'frigopak.com.tr',
  'GLBMD': 'globalmd.com.tr', 'GLYHO': 'globalyatirim.com.tr',
  'HATEK': 'hateks.com.tr',
  'ICBCT': 'icbc.com.tr', 'INVEO': 'inveo.com.tr',
  'ISGYO': 'isgyo.com.tr', 'ISSEN': 'issanayi.com', 'ITTFH': 'ittifakholding.com.tr',
  'JANTS': 'jantsa.com.tr', 'KAYSE': 'kayseriseker.com.tr',
  'KLNMA': 'kalkinma.com.tr', 'KONYA': 'konyacimento.com.tr', 'KOZAA': 'kozamaden.com.tr',
  'KRDMA': 'kardemir.com', 'KRDMB': 'kardemir.com', 'KRDMD': 'kardemir.com',
  'KRTEK': 'kartonsan.com.tr', 'KUTPO': 'kutahyaporselen.com.tr', 'LKMNH': 'lokmanhekim.com.tr',
  'MAKTK': 'makteknik.com.tr', 'MRSHL': 'marshall.com.tr', 'NUHCM': 'nuhcimento.com.tr',
  'OBAMS': 'obamakarna.com', 'ODAS': 'odaselektrik.com.tr', 'ORGE': 'orgeenerji.com.tr',
  'OSTIM': 'ostim.com.tr', 'OZKGY': 'ozakgyo.com', 'PARSN': 'parsan.com.tr',
  'PETUN': 'pinaretbalilk.com.tr', 'PINSU': 'pinar.com.tr', 'POLHO': 'polisan.com.tr',
  'PRKAB': 'prysmiangroup.com', 'QNBFB': 'qnbfinansbank.com', 'QNBFL': 'qnbfinansbank.com',
  'RAYSG': 'raysigorta.com.tr', 'ROYAL': 'royalhali.com', 'SARKY': 'sarkuysan.com.tr',
  'SDTTR': 'sdtuzay.com', 'SOKE': 'sokecimento.com.tr', 'TATGD': 'tatgida.com',
  'TBORG': 'carlsberg.com', 'TOASO': 'tofas.com.tr',
  'TRGYO': 'toranlargyo.com.tr', 'TSKB': 'tskb.com.tr', 'TURSG': 'turkiyesigorta.com.tr',
  'ULUSE': 'ulusoyelektrik.com', 'UNYEC': 'unyecimento.com.tr', 'VAKFN': 'vakifbank.com.tr',
  'VAKKO': 'vakko.com', 'VESBE': 'vestel.com.tr', 'YUNSA': 'yunsa.com',
  'SKBNK': 'sekerbank.com.tr', 'OYAKC': 'oyakcimento.com', 'GUBRF': 'gubretas.com.tr',
  'CEMTS': 'cemtas.com.tr', 'ISGSY': 'isyatirim.com.tr', 'ISMEN': 'isyatirim.com.tr',
  'KARSN': 'karsan.com.tr', 'KATMR': 'katmerciler.com.tr', 'KNFRT': 'konfrut.com.tr',
  'DOGI': 'doganholding.com.tr', 'NTHOL': 'netholding.com', 'ULUUN': 'ulusoyun.com.tr',
  'VERTU': 'verusaturk.com',
  'AFYON': 'afyoncimento.com.tr',
  'TMSN': 'tumosan.com.tr',
  'HEKTS': 'hektas.com.tr', 'SMART': 'smartgunes.com', 'FONET': 'fonet.com.tr',
  'GSDHO': 'gsd.com.tr', 'MERIT': 'meritturizm.com', 'NTGAZ': 'naturelgaz.com.tr',
  'SNKRN': 'senkronsiber.com', 'VBTYZ': 'vfrbt.com.tr', 'BERA': 'beraholding.com.tr'
};
